Mysql wrapper - support async hooks in mysql requests
epsagon/epsagon-node-frameworks pull request #94
Opened 2021-01-17 13:39 UTC by haimrait

2021-01-17 13:52 UTC, galbash approved these changes

2021-01-17 19:23 UTC, galbash requested changes
Small comments

2021-01-17 19:23 UTC, galbash commented on package.json
> +    "lint:js": "eslint --max-warnings=0 ./src/ ./examples/ ./test/unit_tests ./index.js -f table --ext .js --ext .jsxc",
Why?

2021-01-17 19:23 UTC, galbash commented on src/wrappers/express.js
> +        traceContext.destroyAsync(originalAsyncId, true);
I think you should call set reference and then pass the current async I'd (otherwise some stuff won't be caught)

2021-01-18 08:57 UTC, galbash submitted a review, later dismissed

2021-01-18 09:07 UTC, tvaintrob approved these changes

2021-01-18 17:34 UTC, galbash submitted a review, later dismissed

2021-01-18 17:52 UTC, galbash approved these changes

2021-01-18 18:12 UTC, galbash approved these changes

2021-01-18 18:20 UTC, amitlicht approved these changes

2021-01-18 18:22 UTC, merged

2021-01-18 18:36 UTC, ranrib commented
:tada: This PR is included in version 1.25.3 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/epsagon-frameworks/v/1.25.3)
- [GitHub release](https://github.com/epsagon/epsagon-node-frameworks/releases/tag/v1.25.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: